module.exports = {
    MEETINGS: 'meetings',
    MEETING_PARTICIPANTS: 'meetings_participants',
    MEETING_RECORDINGS: 'meetings_recordings',
    LINK_USERS: 'link_users',
    CONTACT_US: 'contact_us_support',
    REQUEST_QUOTE: 'request_quote_details',
    BREAKOUT_ROOM_GROUPS: 'breakout_room_groups',
    PAYMENT_TRANSACTIONS: 'payment_transactions',
    MEETING_PARTICIPANTS_REACTIONS: 'meeting_participants_reactions',
    MEETINGS_CHATS: 'meetings_chats',
    MEETING_CHATGPT_CONVERSATION: 'meeting_chatgpt_conversation',
    MEETING_POLL_RESPONSES: 'meeting_poll_responses',
    WEBINAR_EVENTS: 'webinar_events',
    WEBINAR_EVENT_REGISTRATIONS: 'webinar_event_registrations',
};